get:
  summary: Get all workflows
  operationId: getWorkflows
  responses:
    '200':
      description: Workflow records successfully retrieved
      content:
        application/json:
          schema:
            type: object
            properties:
              workflows:
                $ref: ../components/schemas/WorkflowList.yml

post:
  summary: Create a workflow
  operationId: createWorkflow
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../components/schemas/WorkflowPostRequest.yml
  responses:
    '201':
      description: Workflow record successfully created
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Workflow.yml
    '400':
      $ref: ../components/responses/BadRequest.yml
