services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/check-db-connection.sh:/check-db-connection.sh
      - pg_data:/var/lib/postgresql
  development:
    build:
      context: docker/dev
    environment:
      GOCACHE: /go-cache
    ports:
      - "3000:3000"
    volumes:
      - ./decision-maker:/app
      - ./tmp/.go/pkg:/go/pkg
      - ./tmp/.go-cache:/go-cache
      - .env:/.env
  tool:
    build:
      context: docker/tool
    environment:
      GOCACHE: /go-cache
    volumes:
      - ./decision-maker:/workspace
      - ./tmp/.go/pkg:/go/pkg
      - ./tmp/.go-cache:/go-cache
      - ./api:/api
      - ./db:/db
    env_file:
      - .env
volumes:
  pg_data: