type: object
properties:
  id:
    type: string
    example: pXkHij_kJjXh
  name:
    type: string
    example: Turn on bedroom lights
  userId:
    type: string
    example: gZ84IFg_GsRR
  devices:
    $ref: ./DeviceList.yml
required:
  - id
  - name
  - userId
