// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	AccessTokenScopes  = "accessToken.Scopes"
	RefreshTokenScopes = "refreshToken.Scopes"
)

// LoginUserJSONBody defines parameters for LoginUser.
type LoginUserJSONBody struct {
	// Password The user's password
	Password string `json:"password"`

	// Username User name
	Username string `json:"username"`
}

// LoginUserWithFaceJSONBody defines parameters for LoginUserWithFace.
type LoginUserWithFaceJSONBody struct {
	Embedding []float64 `json:"embedding"`

	// UserId User Id
	UserId string `json:"userId"`
}

// CreateUserJSONBody defines parameters for CreateUser.
type CreateUserJSONBody struct {
	// Password The user's password
	Password string `json:"password"`

	// Username User name
	Username string `json:"username"`
}

// CreateWorkflowJSONBody defines parameters for CreateWorkflow.
type CreateWorkflowJSONBody struct {
	// Name Workflow name
	Name string `json:"name"`
}

// TriggerWorkflowJSONBody defines parameters for TriggerWorkflow.
type TriggerWorkflowJSONBody struct {
	// GestureId Gesture ID
	GestureId int `json:"gestureId"`
}

// UpdateWorkflowJSONBody defines parameters for UpdateWorkflow.
type UpdateWorkflowJSONBody struct {
	// Name Workflow name
	Name *string `json:"name,omitempty"`
}

// AssociateWorkflowDevicesJSONBody defines parameters for AssociateWorkflowDevices.
type AssociateWorkflowDevicesJSONBody struct {
	// Devices An array of device IDs to associate with this workflow
	Devices []string `json:"devices"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody LoginUserJSONBody

// LoginUserWithFaceJSONRequestBody defines body for LoginUserWithFace for application/json ContentType.
type LoginUserWithFaceJSONRequestBody LoginUserWithFaceJSONBody

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody CreateUserJSONBody

// CreateWorkflowJSONRequestBody defines body for CreateWorkflow for application/json ContentType.
type CreateWorkflowJSONRequestBody CreateWorkflowJSONBody

// TriggerWorkflowJSONRequestBody defines body for TriggerWorkflow for application/json ContentType.
type TriggerWorkflowJSONRequestBody TriggerWorkflowJSONBody

// UpdateWorkflowJSONRequestBody defines body for UpdateWorkflow for application/json ContentType.
type UpdateWorkflowJSONRequestBody UpdateWorkflowJSONBody

// AssociateWorkflowDevicesJSONRequestBody defines body for AssociateWorkflowDevices for application/json ContentType.
type AssociateWorkflowDevicesJSONRequestBody AssociateWorkflowDevicesJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Authenticate user
	// (POST /auth/login)
	LoginUser(w http.ResponseWriter, r *http.Request)
	// Biometrically authenticate user
	// (POST /auth/login/face)
	LoginUserWithFace(w http.ResponseWriter, r *http.Request)
	// Issue new access token
	// (GET /auth/refresh)
	RefreshAccessToken(w http.ResponseWriter, r *http.Request)
	// Get all devices
	// (GET /device)
	GetDevices(w http.ResponseWriter, r *http.Request)
	// Delete device by ID
	// (DELETE /device/{id})
	DeleteDevice(w http.ResponseWriter, r *http.Request, id string)
	// Get device by ID
	// (GET /device/{id})
	GetDevice(w http.ResponseWriter, r *http.Request, id string)
	// Check Decision Maker's status
	// (GET /ping)
	Ping(w http.ResponseWriter, r *http.Request)
	// Register new user
	// (POST /user)
	CreateUser(w http.ResponseWriter, r *http.Request)
	// Delete user by ID
	// (DELETE /user/{id})
	DeleteUser(w http.ResponseWriter, r *http.Request, id string)
	// Get all workflows
	// (GET /workflow)
	GetWorkflows(w http.ResponseWriter, r *http.Request)
	// Create a workflow
	// (POST /workflow)
	CreateWorkflow(w http.ResponseWriter, r *http.Request)
	// Trigger a workflow
	// (POST /workflow/trigger)
	TriggerWorkflow(w http.ResponseWriter, r *http.Request)
	// Delete workflow by ID
	// (DELETE /workflow/{id})
	DeleteWorkflow(w http.ResponseWriter, r *http.Request, id string)
	// Get workflow by ID
	// (GET /workflow/{id})
	GetWorkflow(w http.ResponseWriter, r *http.Request, id string)
	// Update workflow
	// (PATCH /workflow/{id})
	UpdateWorkflow(w http.ResponseWriter, r *http.Request, id string)
	// Associate devices to a workflow
	// (PUT /workflow/{id}/devices)
	AssociateWorkflowDevices(w http.ResponseWriter, r *http.Request, id string)
	// Trigger a workflow by ID
	// (POST /workflow/{id}/trigger)
	TriggerWorkflowById(w http.ResponseWriter, r *http.Request, id string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Authenticate user
// (POST /auth/login)
func (_ Unimplemented) LoginUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Biometrically authenticate user
// (POST /auth/login/face)
func (_ Unimplemented) LoginUserWithFace(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Issue new access token
// (GET /auth/refresh)
func (_ Unimplemented) RefreshAccessToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all devices
// (GET /device)
func (_ Unimplemented) GetDevices(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete device by ID
// (DELETE /device/{id})
func (_ Unimplemented) DeleteDevice(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get device by ID
// (GET /device/{id})
func (_ Unimplemented) GetDevice(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Check Decision Maker's status
// (GET /ping)
func (_ Unimplemented) Ping(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register new user
// (POST /user)
func (_ Unimplemented) CreateUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete user by ID
// (DELETE /user/{id})
func (_ Unimplemented) DeleteUser(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all workflows
// (GET /workflow)
func (_ Unimplemented) GetWorkflows(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a workflow
// (POST /workflow)
func (_ Unimplemented) CreateWorkflow(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Trigger a workflow
// (POST /workflow/trigger)
func (_ Unimplemented) TriggerWorkflow(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete workflow by ID
// (DELETE /workflow/{id})
func (_ Unimplemented) DeleteWorkflow(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get workflow by ID
// (GET /workflow/{id})
func (_ Unimplemented) GetWorkflow(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update workflow
// (PATCH /workflow/{id})
func (_ Unimplemented) UpdateWorkflow(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Associate devices to a workflow
// (PUT /workflow/{id}/devices)
func (_ Unimplemented) AssociateWorkflowDevices(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Trigger a workflow by ID
// (POST /workflow/{id}/trigger)
func (_ Unimplemented) TriggerWorkflowById(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoginUserWithFace operation middleware
func (siw *ServerInterfaceWrapper) LoginUserWithFace(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUserWithFace(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshAccessToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshAccessToken(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, RefreshTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshAccessToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDevices operation middleware
func (siw *ServerInterfaceWrapper) GetDevices(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDevices(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDevice operation middleware
func (siw *ServerInterfaceWrapper) DeleteDevice(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDevice(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDevice operation middleware
func (siw *ServerInterfaceWrapper) GetDevice(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDevice(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Ping operation middleware
func (siw *ServerInterfaceWrapper) Ping(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Ping(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkflows operation middleware
func (siw *ServerInterfaceWrapper) GetWorkflows(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkflows(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWorkflow operation middleware
func (siw *ServerInterfaceWrapper) CreateWorkflow(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWorkflow(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerWorkflow operation middleware
func (siw *ServerInterfaceWrapper) TriggerWorkflow(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerWorkflow(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteWorkflow operation middleware
func (siw *ServerInterfaceWrapper) DeleteWorkflow(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteWorkflow(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkflow operation middleware
func (siw *ServerInterfaceWrapper) GetWorkflow(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkflow(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateWorkflow operation middleware
func (siw *ServerInterfaceWrapper) UpdateWorkflow(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateWorkflow(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AssociateWorkflowDevices operation middleware
func (siw *ServerInterfaceWrapper) AssociateWorkflowDevices(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AssociateWorkflowDevices(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerWorkflowById operation middleware
func (siw *ServerInterfaceWrapper) TriggerWorkflowById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerWorkflowById(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.LoginUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login/face", wrapper.LoginUserWithFace)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/refresh", wrapper.RefreshAccessToken)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/device", wrapper.GetDevices)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/device/{id}", wrapper.DeleteDevice)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/device/{id}", wrapper.GetDevice)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ping", wrapper.Ping)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/user", wrapper.CreateUser)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/user/{id}", wrapper.DeleteUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/workflow", wrapper.GetWorkflows)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/workflow", wrapper.CreateWorkflow)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/workflow/trigger", wrapper.TriggerWorkflow)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/workflow/{id}", wrapper.DeleteWorkflow)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/workflow/{id}", wrapper.GetWorkflow)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/workflow/{id}", wrapper.UpdateWorkflow)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/workflow/{id}/devices", wrapper.AssociateWorkflowDevices)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/workflow/{id}/trigger", wrapper.TriggerWorkflowById)
	})

	return r
}

type LoginUserRequestObject struct {
	Body *LoginUserJSONRequestBody
}

type LoginUserResponseObject interface {
	VisitLoginUserResponse(w http.ResponseWriter) error
}

type LoginUser200JSONResponse struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`

	// UserId User ID
	UserId string `json:"userId"`

	// Username User name
	Username string `json:"username"`
}

func (response LoginUser200JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type LoginUser401Response struct {
}

func (response LoginUser401Response) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type LoginUser500JSONResponse struct {
	Message string `json:"message"`

	// Ref A reference code which can be used to find when the error occurred in the logs.
	Ref string `json:"ref"`
}

func (response LoginUser500JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LoginUserWithFaceRequestObject struct {
	Body *LoginUserWithFaceJSONRequestBody
}

type LoginUserWithFaceResponseObject interface {
	VisitLoginUserWithFaceResponse(w http.ResponseWriter) error
}

type LoginUserWithFace200JSONResponse struct {
	AccessToken string `json:"accessToken"`
}

func (response LoginUserWithFace200JSONResponse) VisitLoginUserWithFaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type LoginUserWithFace401Response struct {
}

func (response LoginUserWithFace401Response) VisitLoginUserWithFaceResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type LoginUserWithFace500JSONResponse struct {
	Message string `json:"message"`

	// Ref A reference code which can be used to find when the error occurred in the logs.
	Ref string `json:"ref"`
}

func (response LoginUserWithFace500JSONResponse) VisitLoginUserWithFaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RefreshAccessTokenRequestObject struct {
}

type RefreshAccessTokenResponseObject interface {
	VisitRefreshAccessTokenResponse(w http.ResponseWriter) error
}

type RefreshAccessToken200JSONResponse struct {
	// AccessToken New access token which was just issued
	AccessToken string `json:"accessToken"`
}

func (response RefreshAccessToken200JSONResponse) VisitRefreshAccessTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RefreshAccessToken401Response struct {
}

func (response RefreshAccessToken401Response) VisitRefreshAccessTokenResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type RefreshAccessToken500JSONResponse struct {
	Message string `json:"message"`

	// Ref A reference code which can be used to find when the error occurred in the logs.
	Ref string `json:"ref"`
}

func (response RefreshAccessToken500JSONResponse) VisitRefreshAccessTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDevicesRequestObject struct {
}

type GetDevicesResponseObject interface {
	VisitGetDevicesResponse(w http.ResponseWriter) error
}

type GetDevices200JSONResponse struct {
	// Devices List of devices
	Devices *[]struct {
		// Hostname Device mDNS hostname
		Hostname string `json:"hostname"`

		// Id Device ID
		Id string `json:"id"`

		// Name Device name
		Name *string `json:"name,omitempty"`

		// Type Device type
		Type *string `json:"type,omitempty"`
	} `json:"devices,omitempty"`
}

func (response GetDevices200JSONResponse) VisitGetDevicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDevices500JSONResponse struct {
	Message string `json:"message"`

	// Ref A reference code which can be used to find when the error occurred in the logs.
	Ref string `json:"ref"`
}

func (response GetDevices500JSONResponse) VisitGetDevicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteDeviceRequestObject struct {
	Id string `json:"id"`
}

type DeleteDeviceResponseObject interface {
	VisitDeleteDeviceResponse(w http.ResponseWriter) error
}

type DeleteDevice204Response struct {
}

func (response DeleteDevice204Response) VisitDeleteDeviceResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteDevice404JSONResponse struct {
	Message string `json:"message"`
}

func (response DeleteDevice404JSONResponse) VisitDeleteDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteDevice500JSONResponse struct {
	Message string `json:"message"`

	// Ref A reference code which can be used to find when the error occurred in the logs.
	Ref string `json:"ref"`
}

func (response DeleteDevice500JSONResponse) VisitDeleteDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceRequestObject struct {
	Id string `json:"id"`
}

type GetDeviceResponseObject interface {
	VisitGetDeviceResponse(w http.ResponseWriter) error
}

type GetDevice200JSONResponse struct {
	// Hostname Device mDNS hostname
	Hostname string `json:"hostname"`

	// Id Device ID
	Id string `json:"id"`

	// Name Device name
	Name *string `json:"name,omitempty"`

	// Type Device type
	Type *string `json:"type,omitempty"`
}

func (response GetDevice200JSONResponse) VisitGetDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDevice404JSONResponse struct {
	Message string `json:"message"`
}

func (response GetDevice404JSONResponse) VisitGetDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetDevice500JSONResponse struct {
	Message string `json:"message"`

	// Ref A reference code which can be used to find when the error occurred in the logs.
	Ref string `json:"ref"`
}

func (response GetDevice500JSONResponse) VisitGetDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PingRequestObject struct {
}

type PingResponseObject interface {
	VisitPingResponse(w http.ResponseWriter) error
}

type Ping200JSONResponse struct {
	Status string `json:"status"`
}

func (response Ping200JSONResponse) VisitPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateUserRequestObject struct {
	Body *CreateUserJSONRequestBody
}

type CreateUserResponseObject interface {
	VisitCreateUserResponse(w http.ResponseWriter) error
}

type CreateUser201JSONResponse struct {
	// Id User ID
	Id string `json:"id"`

	// Username User name
	Username string `json:"username"`
}

func (response CreateUser201JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser400JSONResponse struct {
	Message string `json:"message"`
}

func (response CreateUser400JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser500JSONResponse struct {
	Message string `json:"message"`

	// Ref A reference code which can be used to find when the error occurred in the logs.
	Ref string `json:"ref"`
}

func (response CreateUser500JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteUserRequestObject struct {
	Id string `json:"id"`
}

type DeleteUserResponseObject interface {
	VisitDeleteUserResponse(w http.ResponseWriter) error
}

type DeleteUser204Response struct {
}

func (response DeleteUser204Response) VisitDeleteUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteUser404JSONResponse struct {
	Message string `json:"message"`
}

func (response DeleteUser404JSONResponse) VisitDeleteUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteUser500JSONResponse struct {
	Message string `json:"message"`

	// Ref A reference code which can be used to find when the error occurred in the logs.
	Ref string `json:"ref"`
}

func (response DeleteUser500JSONResponse) VisitDeleteUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkflowsRequestObject struct {
}

type GetWorkflowsResponseObject interface {
	VisitGetWorkflowsResponse(w http.ResponseWriter) error
}

type GetWorkflows200JSONResponse struct {
	// Workflows List of workflows
	Workflows *[]struct {
		// Devices List of devices
		Devices *[]struct {
			// Hostname Device mDNS hostname
			Hostname string `json:"hostname"`

			// Id Device ID
			Id string `json:"id"`

			// Name Device name
			Name *string `json:"name,omitempty"`

			// Type Device type
			Type *string `json:"type,omitempty"`
		} `json:"devices,omitempty"`
		Id     string `json:"id"`
		Name   string `json:"name"`
		UserId string `json:"userId"`
	} `json:"workflows,omitempty"`
}

func (response GetWorkflows200JSONResponse) VisitGetWorkflowsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkflows500JSONResponse struct {
	Message string `json:"message"`

	// Ref A reference code which can be used to find when the error occurred in the logs.
	Ref string `json:"ref"`
}

func (response GetWorkflows500JSONResponse) VisitGetWorkflowsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateWorkflowRequestObject struct {
	Body *CreateWorkflowJSONRequestBody
}

type CreateWorkflowResponseObject interface {
	VisitCreateWorkflowResponse(w http.ResponseWriter) error
}

type CreateWorkflow201JSONResponse struct {
	// Devices List of devices
	Devices *[]struct {
		// Hostname Device mDNS hostname
		Hostname string `json:"hostname"`

		// Id Device ID
		Id string `json:"id"`

		// Name Device name
		Name *string `json:"name,omitempty"`

		// Type Device type
		Type *string `json:"type,omitempty"`
	} `json:"devices,omitempty"`
	Id     string `json:"id"`
	Name   string `json:"name"`
	UserId string `json:"userId"`
}

func (response CreateWorkflow201JSONResponse) VisitCreateWorkflowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateWorkflow400JSONResponse struct {
	Message string `json:"message"`
}

func (response CreateWorkflow400JSONResponse) VisitCreateWorkflowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateWorkflow500JSONResponse struct {
	Message string `json:"message"`

	// Ref A reference code which can be used to find when the error occurred in the logs.
	Ref string `json:"ref"`
}

func (response CreateWorkflow500JSONResponse) VisitCreateWorkflowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type TriggerWorkflowRequestObject struct {
	Body *TriggerWorkflowJSONRequestBody
}

type TriggerWorkflowResponseObject interface {
	VisitTriggerWorkflowResponse(w http.ResponseWriter) error
}

type TriggerWorkflow207JSONResponse []struct {
	DeviceId string `json:"deviceId"`

	// Error Error message if ok is false
	Error *string `json:"error,omitempty"`
	Ok    bool    `json:"ok"`
}

func (response TriggerWorkflow207JSONResponse) VisitTriggerWorkflowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(207)

	return json.NewEncoder(w).Encode(response)
}

type TriggerWorkflow401Response struct {
}

func (response TriggerWorkflow401Response) VisitTriggerWorkflowResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type TriggerWorkflow404JSONResponse struct {
	Message string `json:"message"`
}

func (response TriggerWorkflow404JSONResponse) VisitTriggerWorkflowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type TriggerWorkflow500JSONResponse struct {
	Message string `json:"message"`

	// Ref A reference code which can be used to find when the error occurred in the logs.
	Ref string `json:"ref"`
}

func (response TriggerWorkflow500JSONResponse) VisitTriggerWorkflowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteWorkflowRequestObject struct {
	Id string `json:"id"`
}

type DeleteWorkflowResponseObject interface {
	VisitDeleteWorkflowResponse(w http.ResponseWriter) error
}

type DeleteWorkflow204Response struct {
}

func (response DeleteWorkflow204Response) VisitDeleteWorkflowResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteWorkflow404JSONResponse struct {
	Message string `json:"message"`
}

func (response DeleteWorkflow404JSONResponse) VisitDeleteWorkflowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkflowRequestObject struct {
	Id string `json:"id"`
}

type GetWorkflowResponseObject interface {
	VisitGetWorkflowResponse(w http.ResponseWriter) error
}

type GetWorkflow200JSONResponse struct {
	// Devices List of devices
	Devices *[]struct {
		// Hostname Device mDNS hostname
		Hostname string `json:"hostname"`

		// Id Device ID
		Id string `json:"id"`

		// Name Device name
		Name *string `json:"name,omitempty"`

		// Type Device type
		Type *string `json:"type,omitempty"`
	} `json:"devices,omitempty"`
	Id     string `json:"id"`
	Name   string `json:"name"`
	UserId string `json:"userId"`
}

func (response GetWorkflow200JSONResponse) VisitGetWorkflowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkflow404JSONResponse struct {
	Message string `json:"message"`
}

func (response GetWorkflow404JSONResponse) VisitGetWorkflowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkflow500JSONResponse struct {
	Message string `json:"message"`

	// Ref A reference code which can be used to find when the error occurred in the logs.
	Ref string `json:"ref"`
}

func (response GetWorkflow500JSONResponse) VisitGetWorkflowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateWorkflowRequestObject struct {
	Id   string `json:"id"`
	Body *UpdateWorkflowJSONRequestBody
}

type UpdateWorkflowResponseObject interface {
	VisitUpdateWorkflowResponse(w http.ResponseWriter) error
}

type UpdateWorkflow200JSONResponse struct {
	// Devices List of devices
	Devices *[]struct {
		// Hostname Device mDNS hostname
		Hostname string `json:"hostname"`

		// Id Device ID
		Id string `json:"id"`

		// Name Device name
		Name *string `json:"name,omitempty"`

		// Type Device type
		Type *string `json:"type,omitempty"`
	} `json:"devices,omitempty"`
	Id     string `json:"id"`
	Name   string `json:"name"`
	UserId string `json:"userId"`
}

func (response UpdateWorkflow200JSONResponse) VisitUpdateWorkflowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateWorkflow400JSONResponse struct {
	Message string `json:"message"`
}

func (response UpdateWorkflow400JSONResponse) VisitUpdateWorkflowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateWorkflow404JSONResponse struct {
	Message string `json:"message"`
}

func (response UpdateWorkflow404JSONResponse) VisitUpdateWorkflowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AssociateWorkflowDevicesRequestObject struct {
	Id   string `json:"id"`
	Body *AssociateWorkflowDevicesJSONRequestBody
}

type AssociateWorkflowDevicesResponseObject interface {
	VisitAssociateWorkflowDevicesResponse(w http.ResponseWriter) error
}

type AssociateWorkflowDevices200JSONResponse struct {
	// Devices An array of device IDs associated with this workflow
	Devices []string `json:"devices"`
}

func (response AssociateWorkflowDevices200JSONResponse) VisitAssociateWorkflowDevicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AssociateWorkflowDevices400JSONResponse struct {
	Message string `json:"message"`
}

func (response AssociateWorkflowDevices400JSONResponse) VisitAssociateWorkflowDevicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AssociateWorkflowDevices404JSONResponse struct {
	Message string `json:"message"`
}

func (response AssociateWorkflowDevices404JSONResponse) VisitAssociateWorkflowDevicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AssociateWorkflowDevices500JSONResponse struct {
	Message string `json:"message"`

	// Ref A reference code which can be used to find when the error occurred in the logs.
	Ref string `json:"ref"`
}

func (response AssociateWorkflowDevices500JSONResponse) VisitAssociateWorkflowDevicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type TriggerWorkflowByIdRequestObject struct {
	Id string `json:"id"`
}

type TriggerWorkflowByIdResponseObject interface {
	VisitTriggerWorkflowByIdResponse(w http.ResponseWriter) error
}

type TriggerWorkflowById207JSONResponse []struct {
	DeviceId string `json:"deviceId"`

	// Error Error message if ok is false
	Error *string `json:"error,omitempty"`
	Ok    bool    `json:"ok"`
}

func (response TriggerWorkflowById207JSONResponse) VisitTriggerWorkflowByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(207)

	return json.NewEncoder(w).Encode(response)
}

type TriggerWorkflowById401Response struct {
}

func (response TriggerWorkflowById401Response) VisitTriggerWorkflowByIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type TriggerWorkflowById404JSONResponse struct {
	Message string `json:"message"`
}

func (response TriggerWorkflowById404JSONResponse) VisitTriggerWorkflowByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type TriggerWorkflowById500JSONResponse struct {
	Message string `json:"message"`

	// Ref A reference code which can be used to find when the error occurred in the logs.
	Ref string `json:"ref"`
}

func (response TriggerWorkflowById500JSONResponse) VisitTriggerWorkflowByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Authenticate user
	// (POST /auth/login)
	LoginUser(ctx context.Context, request LoginUserRequestObject) (LoginUserResponseObject, error)
	// Biometrically authenticate user
	// (POST /auth/login/face)
	LoginUserWithFace(ctx context.Context, request LoginUserWithFaceRequestObject) (LoginUserWithFaceResponseObject, error)
	// Issue new access token
	// (GET /auth/refresh)
	RefreshAccessToken(ctx context.Context, request RefreshAccessTokenRequestObject) (RefreshAccessTokenResponseObject, error)
	// Get all devices
	// (GET /device)
	GetDevices(ctx context.Context, request GetDevicesRequestObject) (GetDevicesResponseObject, error)
	// Delete device by ID
	// (DELETE /device/{id})
	DeleteDevice(ctx context.Context, request DeleteDeviceRequestObject) (DeleteDeviceResponseObject, error)
	// Get device by ID
	// (GET /device/{id})
	GetDevice(ctx context.Context, request GetDeviceRequestObject) (GetDeviceResponseObject, error)
	// Check Decision Maker's status
	// (GET /ping)
	Ping(ctx context.Context, request PingRequestObject) (PingResponseObject, error)
	// Register new user
	// (POST /user)
	CreateUser(ctx context.Context, request CreateUserRequestObject) (CreateUserResponseObject, error)
	// Delete user by ID
	// (DELETE /user/{id})
	DeleteUser(ctx context.Context, request DeleteUserRequestObject) (DeleteUserResponseObject, error)
	// Get all workflows
	// (GET /workflow)
	GetWorkflows(ctx context.Context, request GetWorkflowsRequestObject) (GetWorkflowsResponseObject, error)
	// Create a workflow
	// (POST /workflow)
	CreateWorkflow(ctx context.Context, request CreateWorkflowRequestObject) (CreateWorkflowResponseObject, error)
	// Trigger a workflow
	// (POST /workflow/trigger)
	TriggerWorkflow(ctx context.Context, request TriggerWorkflowRequestObject) (TriggerWorkflowResponseObject, error)
	// Delete workflow by ID
	// (DELETE /workflow/{id})
	DeleteWorkflow(ctx context.Context, request DeleteWorkflowRequestObject) (DeleteWorkflowResponseObject, error)
	// Get workflow by ID
	// (GET /workflow/{id})
	GetWorkflow(ctx context.Context, request GetWorkflowRequestObject) (GetWorkflowResponseObject, error)
	// Update workflow
	// (PATCH /workflow/{id})
	UpdateWorkflow(ctx context.Context, request UpdateWorkflowRequestObject) (UpdateWorkflowResponseObject, error)
	// Associate devices to a workflow
	// (PUT /workflow/{id}/devices)
	AssociateWorkflowDevices(ctx context.Context, request AssociateWorkflowDevicesRequestObject) (AssociateWorkflowDevicesResponseObject, error)
	// Trigger a workflow by ID
	// (POST /workflow/{id}/trigger)
	TriggerWorkflowById(ctx context.Context, request TriggerWorkflowByIdRequestObject) (TriggerWorkflowByIdResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// LoginUser operation middleware
func (sh *strictHandler) LoginUser(w http.ResponseWriter, r *http.Request) {
	var request LoginUserRequestObject

	var body LoginUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LoginUser(ctx, request.(LoginUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LoginUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginUserResponseObject); ok {
		if err := validResponse.VisitLoginUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LoginUserWithFace operation middleware
func (sh *strictHandler) LoginUserWithFace(w http.ResponseWriter, r *http.Request) {
	var request LoginUserWithFaceRequestObject

	var body LoginUserWithFaceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LoginUserWithFace(ctx, request.(LoginUserWithFaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LoginUserWithFace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginUserWithFaceResponseObject); ok {
		if err := validResponse.VisitLoginUserWithFaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshAccessToken operation middleware
func (sh *strictHandler) RefreshAccessToken(w http.ResponseWriter, r *http.Request) {
	var request RefreshAccessTokenRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshAccessToken(ctx, request.(RefreshAccessTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshAccessToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshAccessTokenResponseObject); ok {
		if err := validResponse.VisitRefreshAccessTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDevices operation middleware
func (sh *strictHandler) GetDevices(w http.ResponseWriter, r *http.Request) {
	var request GetDevicesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDevices(ctx, request.(GetDevicesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDevices")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDevicesResponseObject); ok {
		if err := validResponse.VisitGetDevicesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteDevice operation middleware
func (sh *strictHandler) DeleteDevice(w http.ResponseWriter, r *http.Request, id string) {
	var request DeleteDeviceRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteDevice(ctx, request.(DeleteDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteDeviceResponseObject); ok {
		if err := validResponse.VisitDeleteDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDevice operation middleware
func (sh *strictHandler) GetDevice(w http.ResponseWriter, r *http.Request, id string) {
	var request GetDeviceRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDevice(ctx, request.(GetDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDeviceResponseObject); ok {
		if err := validResponse.VisitGetDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Ping operation middleware
func (sh *strictHandler) Ping(w http.ResponseWriter, r *http.Request) {
	var request PingRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Ping(ctx, request.(PingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Ping")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PingResponseObject); ok {
		if err := validResponse.VisitPingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateUser operation middleware
func (sh *strictHandler) CreateUser(w http.ResponseWriter, r *http.Request) {
	var request CreateUserRequestObject

	var body CreateUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUser(ctx, request.(CreateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateUserResponseObject); ok {
		if err := validResponse.VisitCreateUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteUser operation middleware
func (sh *strictHandler) DeleteUser(w http.ResponseWriter, r *http.Request, id string) {
	var request DeleteUserRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteUser(ctx, request.(DeleteUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteUserResponseObject); ok {
		if err := validResponse.VisitDeleteUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWorkflows operation middleware
func (sh *strictHandler) GetWorkflows(w http.ResponseWriter, r *http.Request) {
	var request GetWorkflowsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetWorkflows(ctx, request.(GetWorkflowsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWorkflows")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetWorkflowsResponseObject); ok {
		if err := validResponse.VisitGetWorkflowsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateWorkflow operation middleware
func (sh *strictHandler) CreateWorkflow(w http.ResponseWriter, r *http.Request) {
	var request CreateWorkflowRequestObject

	var body CreateWorkflowJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateWorkflow(ctx, request.(CreateWorkflowRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateWorkflow")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateWorkflowResponseObject); ok {
		if err := validResponse.VisitCreateWorkflowResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TriggerWorkflow operation middleware
func (sh *strictHandler) TriggerWorkflow(w http.ResponseWriter, r *http.Request) {
	var request TriggerWorkflowRequestObject

	var body TriggerWorkflowJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TriggerWorkflow(ctx, request.(TriggerWorkflowRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TriggerWorkflow")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TriggerWorkflowResponseObject); ok {
		if err := validResponse.VisitTriggerWorkflowResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteWorkflow operation middleware
func (sh *strictHandler) DeleteWorkflow(w http.ResponseWriter, r *http.Request, id string) {
	var request DeleteWorkflowRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteWorkflow(ctx, request.(DeleteWorkflowRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteWorkflow")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteWorkflowResponseObject); ok {
		if err := validResponse.VisitDeleteWorkflowResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWorkflow operation middleware
func (sh *strictHandler) GetWorkflow(w http.ResponseWriter, r *http.Request, id string) {
	var request GetWorkflowRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetWorkflow(ctx, request.(GetWorkflowRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWorkflow")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetWorkflowResponseObject); ok {
		if err := validResponse.VisitGetWorkflowResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateWorkflow operation middleware
func (sh *strictHandler) UpdateWorkflow(w http.ResponseWriter, r *http.Request, id string) {
	var request UpdateWorkflowRequestObject

	request.Id = id

	var body UpdateWorkflowJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateWorkflow(ctx, request.(UpdateWorkflowRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateWorkflow")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateWorkflowResponseObject); ok {
		if err := validResponse.VisitUpdateWorkflowResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AssociateWorkflowDevices operation middleware
func (sh *strictHandler) AssociateWorkflowDevices(w http.ResponseWriter, r *http.Request, id string) {
	var request AssociateWorkflowDevicesRequestObject

	request.Id = id

	var body AssociateWorkflowDevicesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AssociateWorkflowDevices(ctx, request.(AssociateWorkflowDevicesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AssociateWorkflowDevices")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AssociateWorkflowDevicesResponseObject); ok {
		if err := validResponse.VisitAssociateWorkflowDevicesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TriggerWorkflowById operation middleware
func (sh *strictHandler) TriggerWorkflowById(w http.ResponseWriter, r *http.Request, id string) {
	var request TriggerWorkflowByIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TriggerWorkflowById(ctx, request.(TriggerWorkflowByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TriggerWorkflowById")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TriggerWorkflowByIdResponseObject); ok {
		if err := validResponse.VisitTriggerWorkflowByIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xba1PbOPf/Kvp7/zN9k+ZeoMw8L7gsELaBLpdCtw/TUayTWMSWXElOMDv57s9IvsdO",
	"mtC0lO2+C7Yk69x+53eOxN+WzT2fM2BKWrt/WwKkz5kE80f26nP6/PM+JhfwJQCpoiFMATM/se+71MaK",
	"cta4l5zpZ9J2wMP6ly+4D0LRaGUPpMQj0D/hAXu+C9au9ar1tl1vdd/UO/V2p95qNl8hKhHjCmE0wS4l",
	"iPpWzVKhr0dLJSgbWbNZzRLwJaACiLX7KV35Lh3IB/dgK2umRxKQtqC+3qO1a+1jghJZZrVqcXtMgWDY",
	"vQQxAfG7EFxsWm7JPUATECGSPth0SG0E+jsoGV2SWYs81IsU5dlDAoYggNmAbE4ATR1qO8jGDA0ABRII",
	"UhwNKSNo6gBDyoH4S9y2AyGAIBo9dflI1q1abpPDE8d5OO50dggfHR9NTtTe7eXJytaINryKTRJ9o0jh",
	"KNL4IuuccbUXKIcL+qg/OK+QM65Q7v2SVY54wMimDRswPHAh1bmIXA30L5sLslFf1qJGQuh30Tbngzh+",
	"+vkQJtSGshAOl4phD8qKjGYg7/DsEqWj8u7hYEbC1y3cHnTsustt7FZ5LSULl+4dFtbzb8cn9P7z+PT+",
	"1qlaaek2S7vbByI495CLPb9qtejBgtXMy/xq7+jIUV81HtX2TXVVNmFtsWXe0Qhci9vRTxEfImLGyPyW",
	"PuVtV20Lrfp5rcbjC9qZ1SrW6pI3sDUsrvXwyD++fzcO3gdXzWytA0dQqTwskWu0NLurWVSBZ/zr/w1q",
	"Wb81MskbseSNxW6a2sfCQuBwqeauBB2NQFwqrAJZdvBIdT1SDFM8sFvtDoFh981WlXdAAvpFe/yex2hE",
	"h4iPdb4aYlcW/YXEXskVGuoIRTwCWQZqysW46pN8XNiiEgGkowacu4BZyeFS4cz0FR3uWoIo66kqTvXI",
	"+Sgd/bXT7R2NPh/Li4sqMQKpsbwqUs1qpTi1MeU2V0quFl3p8isKe8PFeOjy6SLHeLqTmohNAW59GMtm",
	"XAWCaQcZJEGpw0guUu68Ky83SJUOYxvEi62pyOVANY1HzUPVEihaKH0ibFFCDVZmtdtbsi+2bi7OJt5+",
	"eTWXTigboQUr4g87Z9Ppw0ngdI6/Ca9S9yohls7IYAeCqvBSD448Dds2SHnFx2CoxQCwAHHEhYeVtWud",
	"3lxZ80l+j6FoEjq9uULKzIyTvUEGs0Jmd0cpPyaLAqSz1pdQPGmdL2k5KRvyqlRqU0k5Q308BoH23vf0",
	"XKqM01a+nICQ0dxmvVlvGVD0gWGfWrtWp96s66TjY+UYVTZwoJyGy0fUCOjzKr/UTBCY0pQOENZ8WKAJ",
	"jX5oj0GYEeRjKadckDp6x0cj7TaGElOJpjhE2J3iUKIRMBBYgUQYMZjGRmkkKjPqQj6mQnNojTOGRBpv",
	"e6f3aFA3CkaQap+T8BuoZ7LjssBXjmH94pVMxSqSrPhhq935seidrlzLdl9NcrNZOgeaB7kCtd1srqW4",
	"Cim0v9aSqMKGpeeMqEUpansuaDPpITx1Bsc2PaenvevHXuuM9mSPXbyxD3pbvbF/++Hg9G0dwtNHctOj",
	"57T30L/vN8+uPnbOD8fTHp3SgXek/ro0gyf4uDu6OH7r6ucfby4UvunSc3YRkptr2fNchxz0tvpX1w9n",
	"973H86u9sM+a9T/610eyd3jFjrzwuMP69Li/dfL26Ozo+uJ82Jk625fel1P/9Z8fOs0FFWUBJDYoGb45",
	"avbu+cPZox32H/vd/qPdHP5Zv992b6/u/zj3Tt3+ZO/DZ6fZa5HL4Ra7vj14YPcnN/3268PpwwcX+svz",
	"389MVOJd1vI+n/ehOcWvUuqZLeEcmBEkA7PkMHBdQ5C7zdaiBJYGUGOFinpWs95EMfaEpapaJyYVBp6H",
	"RTiPyFpB5n0OzBtDHBeqayG6noXAGwAhlI2qoZxwiJpLCZgjXIx9hKWh6RKkyU6cuSGCByqVREMuEEY2",
	"D3wXNNWRYHNG5BK4v6HKOdLCbAr2U/EKwfqpWW+1O612u9ve6tSa9eZOd6e73dnpdt7WmvXO9la3097a",
	"ftvuvqm9btbfdNudne1Oe2erm+c9w4QZEB4M3Fz/iQXeAERVRbY8GMkawbgofjJ5f3ym2IvSQ0KDfomM",
	"MGeHvJS/FkjtU+6BEtTGrhsWRJqHrBg+9E5GUAFXxxnSZKwxBptBiAKpMWoOhcqQchG93ptLIt/g7Ev9",
	"ea7NOL/vqMU8xRLdB1IhKmUAxXD/pcOgpK9IQS8sFuLa1VTvRZ746U5XzFmw9LR4Je+OYoSkbecF0aEQ",
	"Rm7cPMCui4CMIGl3zjXNymFxDOow7YxuMBw20xqareArcb85OhyQBRdBQiMQTH6IhQsAMG9gYyXXTbvQ",
	"Ocs2/qZkFqnMBVXZUNfPjRnjnqiHle1o1NPPRnQCDPUOy7aNJsb9YF0zCuyBAiHNfhefJ1BmqlyV6zCZ",
	"pleRK9Rytp+P/ruSL3UXHhREhivaLVIFiUK8+/QQj492ntf2sf1i2w1CreRZbXE069paM0nNngW4WBlL",
	"8yc4QBrcz2399ZDkiQceX4GGJcjw8n1M+03RwTTA+HGdU+lq1xKisg4Y8TllSlduGCmQCoQp1UIeCGS7",
	"FJhCVNMSD5gyRiu72nv9qY1mEJmeRmWkiI+/SjXiaXcrZY5CB5VKFPhRMytgLFk70/GBA/YYFSe9kij+",
	"oFF4kJwLVdbdFzCiRrkRkTV1N2dxZMtQKvDq6DpueEjkaWY4ABQw+iWA/yup/EAAVvBvU3RTTdHW9wSp",
	"66jmqS74ROwYlQz3qaCSu3H0nUu91K8Tr86CYR1yY+JhLWoT+/7S1Jb1NX8QrYkt+muQGmOzXMaZ5s6K",
	"VyxX0vPO5BZVjIRVbOYmdza6wVSTHbk+/fhy9YIlmfFCSpZMObPagsQWZaI4rSXj6+iIC4RN8zEtR+Nk",
	"l4xBEgD9N2g2OzZGjoDhf35Lbd7AUnKbYgWJwuJC1YyHpW/tBo5G1RdkzfTQeVOZszq5paYuJbhVLyzM",
	"ZbsF9zaePb1lh/hf9feiu9vGHOQnT3UrB00aCdNMITlYbKjoptVijhhfxSpGic1FtEmSKwWj5OhovjoC",
	"qQIBNcPa9TtzLZWpucYrMXBdDon4mxuPiXhbVQccx9GruQPHdurYlCkYxUQi7//Zkk8Lgu21xPm2K3jF",
	"W3Xl2y2lQHkP4nVcxMV+ggTIwFVyw73Ol08/kjBZGGhr8M40zNbinrloWco/U/T7kRx0KeRumIc+hTam",
	"Kv+2bti6lssxyOc3W/OnzMf/wL5Y2dl87S4VlZtPcN45c673k5LZaMfP6tM/OXkucYTZCwnEwJh2o8T4",
	"h6P9XEBVpOhG7pzQD6ruKiWRYWrLXOThXKF55UDyb0JowEmIpMMDlyBtVExZ/uQtPnmPBwwA+ViYVsTX",
	"8gkldfSRB8gz91kl11x6rn+u2bcAj0/yIDEU3CssXtM4JKnnuyHinkdV/B0vG5qXRUuHFaJGaInDGqLD",
	"nPCJjDL9YKuG2jXTxu7UsvsRxZ1OqXKim1nprGRGQQ9T6rqIZV+pnFOGpb0FcPZiASrnpeWr5ZrOZ/9h",
	"hHqHkX+mjmuUHV2gy4A6LS1W/6+H0uX48r+xSOvuO9zq+jZdpIogz6GJygPB3JYUz+Xv79R7f/k0KkPh",
	"SgSuAvandToqiTwiVICt3LBmPIgHCjEAEl37ijsCX+1q7IfmPuQzk/5/+w//1P5Degpi1tHrRh4WCNfa",
	"tRrYp9bsbva/AAAA//9NWF2BOUAAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
