openapi: 3.0.0
info:
  title: Decision Maker API
  description: Decision Maker API
  version: 0.0.1
servers:
  - url: /api
paths:
  /ping:
    get:
      summary: Check Decision Maker's status
      operationId: ping
      description: Use this endpoint as a tester for your client implementation.
      responses:
        '200':
          description: Decision Maker is up and running
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                required:
                  - status
  /user:
    post:
      summary: Register new user
      operationId: createUser
      description: Register a new user onto the system. Usernames must be unique!
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: User name
                  example: caiocotts
                password:
                  type: string
                  description: The user's password
                  example: password123
              required:
                - username
                - password
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/BadRequest'
  /user/{id}:
    delete:
      summary: Delete user by ID
      operationId: deleteUser
      description: Delete the user matching the given ID.
      security:
        - accessToken: []
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: string
      responses:
        '204':
          description: User record successfully deleted
        '404':
          $ref: '#/components/responses/NotFound'
  /auth/login:
    post:
      summary: Authenticate user
      operationId: loginUser
      description: Authenticate a user via username and password. Logging in this way always generates a new access/refresh token pair.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: User name
                  example: caiocotts
                password:
                  type: string
                  description: The user's password
                  example: password123
              required:
                - username
                - password
      responses:
        '200':
          description: User authenticated successfully
          content:
            application/json:
              schema:
                type: object
                description: User info, access and refresh tokens
                properties:
                  userId:
                    type: string
                    description: User ID
                    example: gZ84IFg_GsRR
                  username:
                    type: string
                    description: User name
                    example: caiocotts
                  accessToken:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
                  refreshToken:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiaWF0IjoxNzcyMzM4Mzc0fQ.j7lXTjKOmJlMvAV_h0I1dSf6nUXCxnjHWM2-DwxVleM
                required:
                  - userId
                  - username
                  - accessToken
                  - refreshToken
        '401':
          $ref: '#/components/responses/NotAuthorized'
  /auth/login/face:
    post:
      summary: Biometrically authenticate user
      operationId: loginUserWithFace
      description: Authenticate a user via face embedding. Logging in this way does not generate a refresh token as the session only exists for a couple of seconds.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: User Id
                  example: gZ84IFg_GsRR
                embedding:
                  type: array
                  items:
                    type: number
                  example:
                    - 0.1231224263
                    - 0.08484738439
                    - 0.376432679245
                    - -0.54238732864
              required:
                - userId
                - embedding
      responses:
        '200':
          description: User authenticated successfully
          content:
            application/json:
              schema:
                type: object
                description: Access token
                properties:
                  accessToken:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
                required:
                  - accessToken
        '401':
          $ref: '#/components/responses/NotAuthorized'
  /auth/refresh:
    get:
      summary: Issue new access token
      operationId: refreshAccessToken
      description: Generate a new access token by using a refresh token.
      security:
        - refreshToken: []
      responses:
        '200':
          description: New access token issued successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: New access token which was just issued
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
                required:
                  - accessToken
        '403':
          $ref: '#/components/responses/Forbidden'
  /device:
    get:
      summary: Get all devices
      operationId: getDevices
      description: Get a list of all edge devices on the network.
      security:
        - accessToken: []
      responses:
        '200':
          description: Device records successfully retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  devices:
                    $ref: '#/components/schemas/DeviceList'
    post:
      summary: Create a device
      operationId: createDevice
      description: Register a new device onto the system. (This should be used by edge devices who wish to publish their IPs)
      security:
        - accessToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ip:
                  type: string
                  description: Device IP
                  example: 192.168.1.18
              required:
                - ip
      responses:
        '201':
          description: Device record successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '400':
          $ref: '#/components/responses/BadRequest'
  /device/{id}:
    get:
      summary: Get device by ID
      operationId: getDevice
      description: Get information relating to the device matching the given ID.
      security:
        - accessToken: []
      parameters:
        - name: id
          in: path
          description: Device ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Device record successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      summary: Delete device by ID
      operationId: deleteDevice
      description: Delete the device matching the given ID.
      security:
        - accessToken: []
      parameters:
        - name: id
          in: path
          description: Device ID
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Device record successfully deleted
        '404':
          $ref: '#/components/responses/NotFound'
  /workflow:
    get:
      summary: Get all workflows
      operationId: getWorkflows
      description: Get a list of all workflows in the system.
      security:
        - accessToken: []
      responses:
        '200':
          description: Workflow records successfully retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  workflows:
                    $ref: '#/components/schemas/WorkflowList'
    post:
      summary: Create a workflow
      operationId: createWorkflow
      description: Create a new workflow. For adding devices to the workflow see <a href=#operation/associateWorkflowDevices>associateWorkflowDevices</a>.
      security:
        - accessToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Workflow name
                  example: Turn on bedroom lights
              required:
                - name
      responses:
        '201':
          description: Workflow record successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '400':
          $ref: '#/components/responses/BadRequest'
  /workflow/trigger:
    post:
      summary: Trigger a workflow
      operationId: triggerWorkflow
      description: Trigger the workflow corresponding to the given hand gesture, for the currently authenticated user.
      security:
        - accessToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                gestureId:
                  type: string
                  description: Gesture ID
                  example: '2'
              required:
                - gestureId
      responses:
        '200':
          description: Workflow triggered
        '401':
          $ref: '#/components/responses/NotAuthorized'
  /workflow/{id}:
    get:
      summary: Get workflow by ID
      operationId: getWorkflow
      description: Get information relating to the workflow matching the given ID.
      security:
        - accessToken: []
      parameters:
        - name: id
          in: path
          description: Workflow ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Workflow record successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      summary: Delete workflow by ID
      operationId: deleteWorkflow
      description: Delete the workflow matching the given ID.
      security:
        - accessToken: []
      parameters:
        - name: id
          in: path
          description: Workflow ID
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Workflow record successfully deleted
        '404':
          $ref: '#/components/responses/NotFound'
    patch:
      summary: Update workflow
      operationId: updateWorkflow
      description: Update workflow information. For adding devices to the workflow see <a href=#operation/associateWorkflowDevices>associateWorkflowDevices</a>.
      security:
        - accessToken: []
      parameters:
        - name: id
          in: path
          description: Workflow ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Workflow name
                  example: Turn on bedroom lights
      responses:
        '200':
          description: Workflow record successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
  /workflow/{id}/devices:
    put:
      summary: Associate devices to a workflow
      operationId: associateWorkflowDevices
      description: Associate new devices to a workflow. The request body should contain all devices which should be part of the workflow matching the given id. You may also use this endpoint for removing devices from the workflow, by simply ommiting them from the request body. That is to say, if a workflow contains devices 1, 2, and 3, by using this endpoint with only devices 1 and 3, the workflow will now contain only devices 1 and 3.
      security:
        - accessToken: []
      parameters:
        - name: id
          in: path
          description: Workflow ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                devices:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                        description: Device ID
                        example: pXkHij_kJjXh
                    required:
                      - id
              required:
                - devices
      responses:
        '200':
          description: Device associated to workflow successfully
          content:
            application/json:
              schema:
                properties:
                  devices:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: Device ID
                          example: pXkHij_kJjXh
                      required:
                        - id
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
components:
  securitySchemes:
    accessToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: An access JWT token
    refreshToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: A refresh JWT token
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: User ID
          example: gZ84IFg_GsRR
        username:
          type: string
          description: User name
          example: caiocotts
      required:
        - id
        - username
    Device:
      type: object
      properties:
        id:
          type: string
          description: Device ID
          example: pXkHij_kJjXh
        ip:
          type: string
          description: Device IP
          example: 192.168.1.18
        name:
          type: string
          description: Device name
          example: Bedroom lamp
        type:
          type: string
          description: Device type
          example: Light
      required:
        - id
        - ip
    DeviceList:
      type: array
      description: List of devices
      items:
        $ref: '#/components/schemas/Device'
      example:
        - id: pXkHij_kJjXh
          ip: 192.168.1.18
          name: Bedroom lamp
        - id: xzoYPLkuPuT0
          ip: 192.168.1.42
          name: Christmas light
    Workflow:
      type: object
      properties:
        id:
          type: string
          example: pXkHij_kJjXh
        name:
          type: string
          example: Turn on bedroom lights
        userId:
          type: string
          example: gZ84IFg_GsRR
        devices:
          $ref: '#/components/schemas/DeviceList'
      required:
        - id
        - name
        - userId
    WorkflowList:
      type: array
      description: List of workflows
      items:
        $ref: '#/components/schemas/Workflow'
      example:
        - id: pXkHij_kJjXh
          name: Turn on bedroom lights
          userId: gZ84IFg_GsRR
        - id: XXdBr6WRNvmB
          name: Turn on living room lights
          userId: aV8NwwxHuh3G
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: '''192.145.3.23.100'' is not a valid ip'
            required:
              - message
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: unable to find requested record
            required:
              - message
    NotAuthorized:
      description: Not Authorized
    Forbidden:
      description: Forbidden
