# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
openapi.yml:
  info-license:
    - '#/info'
paths/ping.yml:
  security-defined:
    - '#/get'
  operation-4xx-response:
    - '#/get/responses'
paths/user.yml:
  security-defined:
    - '#/post'
paths/auth_login.yml:
  security-defined:
    - '#/post'
paths/device.yml:
  operation-4xx-response:
    - '#/get/responses'
paths/workflow.yml:
  operation-4xx-response:
    - '#/get/responses'
